set help(categories) "flow hier dbs synth init ilm mmmc power place opt cts hold route extract noise report distribute misc"
set help(all,categories) $help(categories)
set help(synth,categories) "synth"
set help(ilm,categories) "ilm"
set help(init,categories) "init ilm mmmc power report"
set help(place,categories) "place dbs report"
set help(prects,categories) "opt dbs report"
set help(cts,categories) "cts dbs report"
set help(opt,categories) "opt"
set help(postcts,categories) "opt dbs report"
set help(postcts_hold,categories) "opt hold dbs report"
#set help(hold) "opt hold dbs report"
set help(route,categories) "route dbs report"
set help(postroute,categories) "opt extract noise dbs report"
set help(postroute_hold,categories) "route extract noise hold dbs report"
set help(signoff,categories) "extract noise"
set help(flow,categories) "flow"
set help(control,categories) "flow"
set help(mmmc,categories) "mmmc"
set help(timing,categories) "mmmc"
set help(noise,categories) "noise"
set help(dbs,categories) "dbs"
set help(power,categories) "power"
set help(distribute,categories) "distribute"
set help(misc,categories) "misc"
set color(flow) #ccff66
set color(dbs) #ffcc66
set color(init) #ccff66
set color(mmmc) #ffcc66
set color(power) #ccff66
set color(place) #ffcc66
set color(opt) #ccff66
set color(cts) #ffcc66
set color(route) #ccff66
set color(extract) #ffcc66
set color(noise) #ccff66
set color(report) #ffcc66
set color(distribute) #ccff66
set color(misc) #ffcc66
# Flow Control
set help(flow,none,steps) "default: init place prects cts postcts postcts_hold route postroute postroute_hold signoff"
set help(flow,none,mode)  "FLAT hier user" 
set help(flow,none,flat)  "none partial full"
#set help(flow,flow)  "mmmc"
set help(flow,none,hier_flow_type) "1pass 2pass"
set help(flow,none,black_box) "TRUE false"
set help(flow,insert_partition_feedthrough,insert_feedthrough) "TRUE false"
set help(flow,set_place_mode,placement_based_ptn) "true FALSE"
set help(flow,create_proto_model,use_flexmodels) "true FALSE"
set help(flow,create_ps_per_micron_model,use_proto_net_delay_model) "true FALSE"
set help(flow,derive_timing_budget,budget_mode) "trial_ipo proto_net_delay_model giga_opt"
set help(flow,replace_proto_model,flexmodel_as_ptn) "true FALSE"
set help(flow,create_proto_model,flexmodel_art_based) "true FALSE"

set help(flow,set_analysis_mode,enable_aocv) "true FALSE"
set help(flow,set_analysis_mode,enable_cppr) "true FALSE"
set help(flow,set_analysis_mode,enable_ocv) "pre_prects pre_postcts pre_postroute PRE_POSTROUTE_HOLD pre_signoff false"
set help(flow,set_delay_cal_mode,enable_si_aware) "true FALSE"
set help(flow,set_delay_cal_mode,enable_ss) "pre_place pre_prects pre_postcts pre_postroute pre_postroute_hold pre_signoff FALSE"

set help(flow,none,enable_pac) "true FALSE"
set help(flow,none,enable_dlm) "true FALSE"
set help(flow,none,fix_hold) "TRUE false"
set help(flow,none,fix_litho) "true FALSE"
set help(flow,none,high_timing_effort) "true FALSE"
set help(flow,none,run_clp) "TRUE false"
set help(flow,none,run_lec) "true FALSE"
set help(flow,none,skip_cts) "true FALSE"
set help(flow,none,skip_si) "true FALSE"
set help(flow,none,skip_signoff_checks) "true FALSE"

set help(flow,none,abort) "true FALSE"
set help(flow,none,batch) "TRUE false" 
set help(flow,none,save_on_catch) "TRUE false" 
set help(flow,none,catch_errors) "TRUE false" 

# Library Setup
set help(mmmc,create_library_set,library_sets) "List of library sets"
set help(mmmc,create_library_set,<ls>,timing) "List of library files"  
set help(mmmc,create_library_set,<ls>,aocv) "AOCV table file"
set help(mmmc,create_library_set,<ls>,si)  "List of CDB files"
set help(mmmc,create_rc_corner,rc_corners) "List of RC corners"
set help(mmmc,create_rc_corner,<rc>,P) "Process multiplier"
set help(mmmc,create_rc_corner,<rc>,T) "Temperature"
set help(mmmc,create_rc_corner,<rc>,V) "Voltage" 
set help(mmmc,create_rc_corner,<rc>,cap_table) "Captable file"
set help(mmmc,create_rc_corner,<rc>,post_route_cap_factor) "float (triplet)"
set help(mmmc,create_rc_corner,<rc>,post_route_clk_cap_factor) "float (triplet)"
set help(mmmc,create_rc_corner,<rc>,post_route_clk_res_factor) "float (triplet)"
set help(mmmc,create_rc_corner,<rc>,post_route_res_factor) "float"
set help(mmmc,create_rc_corner,<rc>,pre_route_cap_factor) "float"
set help(mmmc,create_rc_corner,<rc>,pre_route_clk_cap_factor) "float"
set help(mmmc,create_rc_corner,<rc>,pre_route_clk_res_factor) "float"
set help(mmmc,create_rc_corner,<rc>,pre_route_res_factor) "float"
set help(mmmc,create_rc_corner,<rc>,qx_tech_file) "QRC techfile"
set help(mmmc,create_op_cond,opconds) "List of opconds"
set help(mmmc,create_op_cond,<opcond>,P) "Process multiplier" 
set help(mmmc,create_op_cond,<opcond>,T) "Temperature"
set help(mmmc,create_op_cond,<opcond>,V) "Voltage"
set help(mmmc,create_op_cond,<opcond>,library_file) "Library file"
set help(mmmc,create_delay_corner,delay_corners) "List of delay corners"
set help(mmmc,create_delay_corner,<dc>,library_set) "Library set"
set help(mmmc,create_delay_corner,<dc>,rc_corner) "RC corner"
set help(mmmc,update_delay_corner,<dc>,power_domains) "List of power domains"
set help(mmmc,create_delay_corner,<dc>,clock_cell_early) "Float"
set help(mmmc,create_delay_corner,<dc>,clock_cell_late) "Float"
set help(mmmc,create_delay_corner,<dc>,clock_net_early) "Float"
set help(mmmc,create_delay_corner,<dc>,clock_net_late) "Float"
set help(mmmc,create_delay_corner,<dc>,data_cell_early) "Float"
set help(mmmc,create_delay_corner,<dc>,data_cell_late) "Float"
set help(mmmc,create_delay_corner,<dc>,data_net_early) "Float"
set help(mmmc,create_delay_corner,<dc>,data_net_late) "Float"
set help(mmmc,create_constraint_mode,constraint_modes) "List of constraint modes"
set help(mmmc,create_constraint_mode,<cm>,pre_cts_sdc) "List of SDC files"
set help(mmmc,update_constraint_mode,<cm>,post_cts_sdc) "List of SDC files" 
set help(mmmc,update_constraint_mode,<cm>,incr_cts_sdc) "List of SDC files (incremental)" 
set help(mmmc,update_constraint_mode,<cm>,ilm_non_sdc_file) "List of ILM constraints"
set help(mmmc,create_analysis_view,setup_analysis_views) "List of analysis views" 
set help(mmmc,create_analysis_view,hold_analysis_views) "List of analysis views" 
set help(mmmc,create_analysis_view,<av>,constraint_mode) "Constraint mode"
set help(mmmc,create_analysis_view,<av>,delay_corner) "Delay corner"

set help(mmmc,set_analysis_view,active_setup_views) "List of active setup views"
set help(mmmc,set_analysis_view,active_hold_views) "List of active hold views"
set help(mmmc,set_analysis_view,<step>,active_setup_views) "List of active setup views per step"
set help(mmmc,set_analysis_view,<step>,active_hold_views) "List of active hold views per step"

set help(mmmc,set_analysis_view,default_setup_view) "Default setup view"
set help(mmmc,set_analysis_view,default_hold_view) "Default hold view"

# Synthesis
set help(synth,set_attribute,enable_pam) "true FALSE"
set help(synth,read_hdl,syn_load_rtl_tcl) "File to load/elaborate RTL"
set help(synth,read_hdl,hdl_search_path) "Verilog RTL search path"
set help(synth,read_hdl,hdl_file_list) "Verilog RTL files"
set help(synth,read_sdc,constraint_modes) "List of constraint modes (default will be used)"
set help(synth,read_sdc,<cm>,pre_cts_sdc) "List of SDC files"
set help(synth,read_def,def_files) "List of def files"
set help(synth,set_attribute,clock_gate_cells) "List of ICG cells"
set help(synth,set_attribute,postload_syn_place_tcl) "RCP pre-place plug-in"
set help(synth,set_attribute,preexport_syn_place_tcl) "RCP post-place plug-in"
set help(synth,set_attribute,preannotation_syn_place_tcl) "RCP pre-import plug-in"
# Design Initialization
set help(init,init_design,netlist) "Netlist files"
set help(init,init_design,netlist_type) "VERILOG vhdl"
set help(init,init_design,design) "Design name"
set help(init,def_in,def_files) "List of def files"
set help(init,init_design,oa_design_lib) "Starting OA design library"
set help(init,init_design,oa_design_cell) "Starting OA design cell"
set help(init,init_design,oa_design_view)  "Starting OA design view"
set help(init,specify_ilm,ilm_list) "List of ILMs"
set help(init,specify_ilm,<ilm>,ilm_dir) "ILM directory for <ilm>"
set help(init,specify_ilm,<ilm>,lef_file) "LEF file for <ilm>"
set help(init,specify_ilm,<ilm>,setup_lib) "Blackbox LIB file for <ilm>"
set help(init,none,enable_flexilm) "Enable the flexIlm hierarchical flow"
set help(init,set_design_mode,process) "Process node (45nms, e.g.)"
set help(init,set_max_route_layer,max_route_layer) "Integer"
set help(init,generate_tracks,generate_tracks) "true FALSE"
set help(init,generate_tracks,honor_pitch) "true FALSE"
set help(init,init_design,assign_buffer) "1 -buffer <buffer>"
#set help(init,init_design,assign_buffer_cell) "<buffer>"
set help(init,set_dont_use,always_on_buffers) "List of AON buffers"
set help(init,set_dont_use,delay_cells) "List of delay cells"
set help(init,set_dont_use,dont_use_list) "List of dont use cells"
set help(init,set_dont_use,dont_use_file) "File w/setDontUse commands"
set help(init,add_end_cap,endcaps) "Endcap cells"
set help(init,add_well_tap,welltaps) "Welltap cells"
set help(init,add_well_tap,welltaps,cell_interval) "Float: (interval) distance in microns"
set help(init,add_well_tap,welltaps,checkerboard) "true FALSE"

# ILM Related
set help(ilm,specify_ilm,ilm_list) "List of ILMs"
set help(ilm,specify_ilm,<ilm>,ilm_dir) "ILM directory for <ilm>"
set help(ilm,specify_ilm,<ilm>,lef_file) "LEF file for <ilm>"
set help(ilm,specify_ilm,<ilm>,setup_lib) "Blackbox LIB file for <ilm>"
set help(ilm,update_constraint_mode,<cm>,ilm_non_sdc_file) "List of ILM constraints"
set help(ilm,none,enable_flexilm) "Enable the flexIlm hierarchical flow"

# Place
set help(place,set_place_mode,place_io_pins) "true FALSE"
set help(place,set_place_mode,clock_gate_aware) "true FALSE"
set help(place,set_place_mode,clock_gate_clone) "true FALSE"
set help(place,set_place_mode,congestion_effort) "low medium high AUTO"
set help(place,specify_spare_gate,spare_cells) "List of spare modules"
set help(place,place_jtag,jtag_cells) "List of jtag modules"
set help(place,place_jtag,jtag_rows) "List of rows to reserve for jtag placement"
set help(place,set_filler_mode,filler_cells) "List of filler cells"
set help(place,set_useful_skew_mode,skew_buffers) "List of buffers for useful skew"
set help(place,set_tie_hilo_mode,tie_cells) "List of tie cells"
set help(place,set_tie_hilo_mode,tie_cells,max_distance) "Float: distance in microns"
set help(place,set_tie_hilo_mode,tie_cells,max_fanout) "Interger: fanout number"
set help(place,set_design_mode,flow_effort) "express STANDARD extreme"
set help(place,set_design_mode,power_effort) "true FALSE"

# Power
set help(mmmc,none,cpf_timing) "true FALSE"

set help(power,read_activity_file,activity_file) "File name"
set help(power,read_activity_file,activity_file_format) "TCF VCD SAIF"
set help(power,set_power_analysis_view,power_analysis_view) "Analysis view for power analysis"
set help(power,none,power_domains) "List of power domains"
set help(power,set_design_mode,flow_effort) "express STANDARD extreme"
set help(power,set_design_mode,power_effort) "true FALSE"

set help(power,load_cpf,cpf_file) "File name" 
set help(power,load_cpf,cpf_isolation) "TRUE or false (Commit isolation rules?)"
set help(power,load_cpf,cpf_keep_rows) "TRUE or false (Keep rows?)"
set help(power,load_cpf,cpf_level_shifter) "TRUE or false (Commit level shifter rules?)"
set help(power,load_cpf,cpf_power_domain) "TRUE or false (Commit power domains?)"
set help(power,load_cpf,cpf_power_switch) "TRUE of false (Commit power switch rules?)"
set help(power,load_cpf,cpf_state_retention) "TRUE or false (Commit state retention rules?)"
set help(power,load_ieee1801,ieee1801_file) "File name" 
set help(power,load_ieee1801,ieee1801_isolation) "TRUE or false (Commit isolation rules?)"
set help(power,load_ieee1801,ieee1801_keep_rows) "TRUE or false (Keep rows?)"
set help(power,load_ieee1801,ieee1801_level_shifter) "TRUE or false (Commit level shifter rules?)"
set help(power,load_ieee1801,ieee1801_power_domain) "TRUE or false (Commit power domains?)"
set help(power,load_ieee1801,ieee1801_power_switch) "TRUE of false (Commit power switch rules?)"
set help(power,load_ieee1801,ieee1801_state_retention) "TRUE or false (Commit state retention rules?)"

set help(power,global_net_connect,power_nets) "List of power nets"
set help(power,global_net_connect,ground_nets) "List of ground nets"
set help(power,global_net_connect,global_nets) "List of global nets"
set help(power,global_net_connect,<global_net>,module) "Module for global net"
set help(power,global_net_connect,<global_net>,pins) "Power pins for global net"
set help(power,global_net_connect,<global_net>,tiehi) "Tiehi global net" 
set help(power,global_net_connect,<global_net>,tielo) "Tielo global net" 



# Clock
set help(cts,cts_engine) "cts CCOPT ccopt_cts"
set help(cts,cts_integration) "native scripted"
set help(cts,specify_clock_tree,cts_cells) "List of CTS cells"
set help(cts,set_ccopt_mode,cts_buffer_cells) "List of CTS buffer cells"
set help(cts,set_ccopt_mode,cts_inverter_cells) "List of CTS inverter cells"
set help(cts,set_ccopt_mode,clock_gate_cells) "List of CTS clock gate cells"
set help(cts,set_ccopt_mode,cts_use_inverters) "true false"
set help(cts,set_cts/ccopt_mode,clk_leaf_bottom_layer) "Layer number"
set help(cts,set_cts/ccopt_mode,clk_leaf_top_layer) "Layer number"
set help(cts,set_cts/ccopt_mode,clk_leaf_extra_space) "Integer (tracks)"
set help(cts,set_cts/ccopt_mode,clk_leaf_ndr) "Valid NDR name"
set help(cts,set_ccopt_mode,clk_max_skew) "Float (nanoseconds)"
set help(cts,set_ccopt_mode,clk_max_slew) "Float (nanoseconds)"
set help(cts,set_cts/ccopt_mode,clk_tree_bottom_layer) "Layer number"
set help(cts,set_cts/ccopt_mode,clk_tree_top_layer) "Layer number"
set help(cts,set_cts/ccopt_mode,clk_tree_extra_space) "Integer (tracks)"
set help(cts,set_cts/ccopt_mode,clk_tree_ndr) "Valid NDR name"
set help(cts,set_ccopt_mode,clk_tree_shield_net) "Global shield net"
set help(cts,set_ccopt_mode,clk_tree_shield_thresh) "Unused at the moment"
set help(cts,set_cts/ccopt_mode,update_io_latency) "Adjust IO latencies"
set help(flow,ccopt_design,postcts_setup_hold) "true FALSE"
set help(cts,ck_eco,clock_eco) "true FALSE"
set help(cts,set_design_mode,flow_effort) "express STANDARD extreme"
set help(cts,set_design_mode,power_effort) "true FALSE"

# Opt
set help(opt,set_opt_mode,all_end_points) "true FALSE"
set help(place,set_place_mode,clock_gate_aware_opt) "true FALSE"
set help(opt,set_opt_mode,critical_range) "true FALSE"
set help(opt,set_opt_mode,congestion_effort) "low medium high AUTO"
set help(opt,set_opt_mode,dynamic_power_effort) "low high"
set help(opt,set_opt_mode,leakage_power_effort) "low high"
set help(opt,set_opt_mode,preserve_assertions) "true FALSE" 
set help(opt,set_opt_mode,resize_shifter_and_iso_insts) "true FALSE" 
set help(opt,set_opt_mode,fix_hold_allow_tns_degradation) "true FALSE"
set help(opt,set_opt_mode,fix_hold_ignore_ios) "true FALSE"
set help(opt,set_opt_mode,useful_skew) "true FALSE"
set help(opt,set_design_mode,flow_effort) "express STANDARD extreme"
set help(opt,set_design_mode,power_effort) "true FALSE"

# Hold
set help(flow,none,fix_hold) "TRUE false"
set help(flow,ccopt_design,postcts_setup_hold) "true FALSE"
set help(flow,opt_design,postroute_setup_hold) "TRUE false"
set help(hold,set_opt_mode,fix_hold_allow_tns_degradation) "true FALSE"
set help(hold,set_opt_mode,fix_hold_ignore_ios) "true FALSE"
set help(hold,set_analysis_view,active_hold_views) "List of active hold views"
set help(hold,set_analysis_view,<step>,active_hold_views) "List of active hold views per step"
set help(mmmc,set_analysis_view,default_setup_view) "Default setup view"
set help(hold,set_analysis_view,default_hold_view) "Default hold view"

# Route
set help(route,set_nanoroute_mode,multi_cut_effort) "MEDIUM high"
set help(route,set_nanoroute_mode,litho_driven_routing) "true FALSE"
set help(route,set_nanoroute_mode,postroute_spread_wires) "true FALSE"
set help(route,set_cts_mode,route_clock_nets) "TRUE false"
set help(route,set_pg_pin_use_signal_route,secondary_pg,cell_pin_pairs) "List of cell:pin pairs"
set help(route,route_pg_pin_use_signal_route,route_secondary_pg_nets) "true FALSE"
set help(route,route_pg_pin_use_signal_route,secondary_pg_nets) "List of global nets for secondary power/ground"
set help(route,route_design,in_route_opt) "FALSE true"

# Extraction
set help(extract,set_extract_rc_mode,postroute_extraction_effort) "LOW medium high"
set help(extract,set_extract_rc_mode,signoff_extraction_effort) "low medium HIGH"
set help(extract,set_extract_rc_mode,coupling_c_thresh) "Float"
set help(extract,set_extract_rc_mode,total_c_thresh) "Float"
set help(extract,set_extract_rc_mode,relative_c_thresh) "Float"

# DFM
set help(dfm,verify_litho,verify_litho) "true FALSE"
set help(dfm,verify_litho,lpa_tech_file) "LPA tech file"
set help(dfm,trim_metal_fill,metalfill) "true FALSE"
set help(dfm,none,metalfill_tcl) "Metalfill plug-in"
set help(dfm,streamOut,gds_files) "GDS file list"
set help(dfm,streamOut,gds_layer_map) "GDS layer map"
set help(dfm,oasisOut,gds_files) "Oasis file list"
set help(dfm,oasisOut,gds_layer_map) "Oasis layer map"

# Noise
set help(noise,set_si_mode,si_analysis_type) "DEFAULT pessimistic"
set help(noise,set_si_mode,delta_delay_threshold) "Float (nanoseconds)"
set help(noise,set_si_mode,acceptable_wns) "Float (nanoseconds)"

# Database
set help(dbs,none,dbs_dir) "Database directory"
set help(dbs,save_design,dbs_format) "FE oa"
set help(dbs,save_design,oa_layout_name) "OA Layout view name"
set help(dbs,save_design,oa_abstract_name) "OA Abstract view name"
set help(dbs,save_design,save_constraints) "true FALSE (Save constraints with DBS?)"
set help(dbs,save_design,save_rc) "true FALSE (Save RCDB with DBS?)"

# Reporting
set help(report,none,rpt_dir) "Reports directory"
set help(report,none,report_power) "TRUE false"
set help(report,none,report_run_time) "TRUE false"
set help(report,none,report_system_info) "true FALSE"
#set help(report,flow_summary) 
set help(report,none,capture_metrics) "true FALSE"
set help(report,none,check_setup) "TRUE false"
set help(report,none,html_summary) "HTML summary file"
set help(report,none,time_info_db) "Time info DB file"
set help(report,none,time_info_rpt) "Time info report file"


# Misc
set help(misc,mail,to) "Mail addresses"
set help(misc,mail,steps) "List of steps"

set help(misc,none,plug_dir) "Plug-in directory"
set help(misc,none,tmp_dir) "TMP directory"
set help(misc,none,log_dir) "LOG directory"

set help(misc,none,version) "Innovus version"
set help(misc,none,vpath) "Make semaphore directory"
set help(misc,none,pac_scratch_dir) "PAC scratch directory (PAC_SCRATCH_DIR)"
set help(misc,none,partition_dir) "PARTITION directory"

set help(misc,none,abutted_design) "Abutted hierarchical design flow"
set help(misc,none,insert_feedthrough) "Insert feedthrough during hierarchical flows"
set help(misc,set_budget_mode,budget_mode) "TRIAL_IPO, giga_opt, ps_pm"
set help(misc,none,use_ps_pm) "Use ps per micron during hierarchical flows"
set help(misc,none,enable_flexilm) "Enable the flexIlm hierarchical flow"
set help(misc,none,use_flexmodels) "Use flexModels during hierarchical flow"
set help(misc,none,flexmodel_as_ptn) "Treat flexModels as partitions"
set help(misc,none,flexmodel_art_based) "Treat flexModels as ART"

set help(distribute,set_distribute_host,distribute) "LOCAL lsf rsh custom"
set help(distribute,set_multi_cpu_usage,local_cpus) "List of hosts"
set help(distribute,set_multi_cpu_usage,remote_hosts) "Integer (number of hosts)"
set help(distribute,set_multi_cpu_usage,cpus_per_remote_host) "Integer (number of cpus)"
set help(distribute,set_distribute_host,lsf,queue) "LSF queue"
set help(distribute,set_distribute_host,lsf,resource) "LSF resources"
set help(distribute,set_distribute_host,lsf,args) "LSF args"
set help(distribute,set_distribute_host,rsh,host_list) "List of hosts"
set help(distribute,set_distribute_host,custom,script) "Custom launch script"

set help(make,make,make_tool) "Encounter executable"
set help(make,make,make_tool_args) "Encounter args"
set help(make,make,make_syn_tool) "RC executable"
set help(make,make,make_syn_tool_args) "RC args"
set help(make,make,make_browser) "Browser"

set help(hier,categories) hier
set help(hier,none,paritition_list) "List of partitions"
set help(hier,none,hier_flow_type) "1pass 2pass"
set help(hier,none,black_box) "TRUE false"
set help(hier,insert_partition_feedthrough,insert_feedthrough) "TRUE false"
set help(hier,set_place_mode,placement_based_ptn) "true FALSE"
set help(hier,create_proto_model,use_flexmodels) "true FALSE"
set help(hier,create_ps_per_micron_model,use_proto_net_delay_model) "true FALSE"
set help(hier,derive_timing_budget,budget_mode) "trial_ipo proto_net_delay_model giga_opt"
set help(hier,replace_proto_model,flexmodel_as_ptn) "true FALSE"
set help(hier,create_proto_model,flexmodel_art_based) "true FALSE"
set help(hier,set_design_mode,use_nrgr) "true FALSE"

